version: '3'
services:
  react-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '8080:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: ["npm", "run", "test"]
