name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t pichi11037/docker-pipeline -f frontend/Dockerfile.dev frontend/.
    - name: Running Docker container
      run: docker run -e CI=true pichi11037/docker-pipeline
